unsuperwhite_v11_example = {
    "inquiry_date": "20241022",
    "age": 24.0,
    "annual_income": 3000000.0,
    "match_data": {
        "cf2": {
            "postal_code": [6008497, 6008497, 6008497],
            "member_industry_classification": [10, 30, 20],
            "contract_date": ["20240718", "20231020", "20170817"],
            "contract_management_classification": [2, 2, 1],
            "product_code": ["R02", None, "Q02"],
            "number_of_payments": [12.0, 6.0, -999.0],
            "contract_amount": [20.0, 50.0, 200.0],
            "credit_limit": [-999999.0, -999999.0, 200.0],
            "cash_advance_credit_limit": [-999999.0, -999999.0, -999999.0],
            "reporting_date": ["20241028", "20240526", "20241030"],
            "outstanding_debt_amount": [2.0, 0.0, 0.0],
            "payment_amount": [18.0, -444444.0, 350.0],
            "cumulative_payment_amount": [18.0, -999999.0, 350.0],
            "payment_history": ["$-$AA-$P$$$A", "$$$-$-", "$A$$$AA$PPPA$A$A$PPPPA$A"],
            "information_type": ["XX", "XX", "XX"],
            "ending_comment": [None, 71, None],
            "additional_comment_n": [None, "some additional comments", None],
            "guarantor_classification": [0, 0, 0],
            "product_code_1": ["R02", None, "Q02"],
            "annual_billing_amount": [-999999.0, -999999.0, -999999.0],
        },
        "ff": {
            "contract_amount": [
                20000.0,
            ],
            "credit_limit": [-999999999.0],
            "latest_payment_date": [None],
            "balance": [2000.0],
            "cash_advance_balance": [-999999999.0],
            "loan_date": [None],
        },
        "hom": {
            "postal_code": [
                5300018,
                5300018,
                5300018,
            ],
            "inquiry_date": [
                "20240711",
                "20240712",
                "20240715",
            ],
            "inquiry_time": ["103030", "151515", "130845"],
            "inquiry_type": [3, 4, 5],
            "product_code_1": ["Q01", "Q03", "R04"],
            "application_amount": [500.0, 0.0, 200.0],
            "number_of_payments": [36.0, 0.0, 24.0],
            "member_industry_classification": [
                30.0,
                20.0,
                99.0,
            ],
        },
    },
    "similar_data": {
        "cf2": {
            "postal_code": [],
            "member_industry_classification": [],
            "contract_date": [],
            "contract_management_classification": [],
            "product_code": [],
            "number_of_payments": [],
            "contract_amount": [],
            "credit_limit": [],
            "cash_advance_credit_limit": [],
            "reporting_date": [],
            "outstanding_debt_amount": [],
            "payment_amount": [],
            "cumulative_payment_amount": [],
            "payment_history": [],
            "information_type": [],
            "ending_comment": [],
            "additional_comment_n": [],
            "guarantor_classification": [],
            "product_code_1": [],
            "annual_billing_amount": [],
        },
        "ff": {
            "contract_amount": [],
            "credit_limit": [],
            "latest_payment_date": [],
            "balance": [],
            "cash_advance_balance": [],
            "loan_date": [],
        },
        "hom": {
            "postal_code": [],
            "inquiry_date": [],
            "inquiry_time": [],
            "inquiry_type": [],
            "product_code_1": [],
            "application_amount": [],
            "number_of_payments": [],
            "member_industry_classification": [],
        },
    },
}